require('dotenv').config()
require('colors')
const path = require('path')
const root = path.join(__dirname, '..', '..')
const createWebpackIndex = require('./create-webpack')
const createNodeIndex = require('./create-node')

console.log('Create index building...'.blue)
;(async function () {
  await createWebpackIndex([root, 'src', 'models', 'data'], 'Model')
  await createWebpackIndex([root, 'src', 'models', 'proto'], 'Model')
  await createWebpackIndex([root, 'src', 'utility', 'function'])
  await createNodeIndex([root, 'src', 'models', 'schema'])
  console.log('build finish'.blue)
})()
